In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('flat.csv')

In [4]:
df1 = pd.read_csv('house.csv')

In [5]:
df.fillna('NA',inplace=True)

C:\Users\ishwa\AppData\Local\Temp\ipykernel_12984\3404714331.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'NA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna('NA',inplace=True)

In [6]:
df1.fillna('NA',inplace=True)

C:\Users\ishwa\AppData\Local\Temp\ipykernel_12984\3896716503.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'NA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df1.fillna('NA',inplace=True)

In [7]:
df.head()

,type,bhk,sector,society,price,price_sqft,plot_area,carpet_area,build_area,super_build_area,bedroom,bathroom,balcony,facing,flat_floor,house_floor,agePossession,Servant Room,Store Room,Pooja Room,Study Room,Others,furnishing_type,luxury_score,Environment,Amenities,Lifestyle,Construction,Management,Grean Area,Connectivity,Safety
0,flat,2.0,33,tulsiani easy in homes,0.4,6722.0,NA,595.0,NA,NA,2.0,2.0,3.0,NA,12.0,NA,New Property,0,0,0,0,0,0,0.0,4,0,4,0,0,0,5,4
1,flat,2.0,61,smart world orchard,1.47,12250.0,NA,1200.0,NA,NA,2.0,2.0,2.0,NA,2.0,NA,Undefined,0,0,0,1,0,0,0.0,0,0,0,0,0,0,0,0
2,flat,2.0,92,parkwood westend,0.7,5204.0,NA,NA,1345.0,NA,2.0,2.0,3.0,NA,5.0,NA,Under Construction,0,0,0,1,0,0,89.0,5,0,4,0,0,0,4,3
3,flat,2.0,36,signature global infinity mall,0.41,6269.0,NA,NA,NA,654.0,2.0,2.0,3.0,NA,3.0,NA,Undefined,0,0,0,0,0,0,72.0,0,0,0,0,0,0,0,0
4,flat,3.0,104,ats triumph,1.8,7860.0,NA,2290.0,NA,NA,3.0,4.0,3.0,NA,14.0,NA,New Property,0,0,0,0,0,0,54.0,0,0,0,5,5,4,5,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2850 entries, 0 to 2849
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   type              2850 non-null   object
 1   bhk               2850 non-null   float64
 2   sector            2850 non-null   object
 3   society           2850 non-null   object
 4   price             2850 non-null   object
 5   price_sqft        2850 non-null   object
 6   plot_area         2850 non-null   object
 7   carpet_area       2850 non-null   object
 8   build_area        2850 non-null   object
 9   super_build_area  2850 non-null   object
 10  bedroom           2850 non-null   object
 11  bathroom          2850 non-null   object
 12  balcony           2850 non-null   object
 13  facing            2850 non-null   object
 14  flat_floor        2850 non-null   object
 15  house_floor       2850 non-null   object
 16  agePossession     2850 non-null   object
 17  Servant Room      2850 non-null   int64
 18  Store Room        2850 non-null   int64
 19  Pooja Room        2850 non-null   int64
 20  Study Room        2850 non-null   int64
 21  Others            2850 non-null   int64
 22  furnishing_type   2850 non-null   int64
 23  luxury_score      2850 non-null   object
 24  Environment       2850 non-null   int64
 25  Amenities         2850 non-null   int64
 26  Lifestyle         2850 non-null   int64
 27  Construction      2850 non-null   int64
 28  Management        2850 non-null   int64
 29  Grean Area        2850 non-null   int64
 30  Connectivity      2850 non-null   int64
 31  Safety            2850 non-null   int64
dtypes: float64(1), int64(14), object(17)
memory usage: 712.6+ KB

In [9]:
df1.head()

,type,bhk,sector,society,price,price_sqft,plot_area,carpet_area,build_area,super_build_area,bedroom,bathroom,balcony,facing,flat_floor,house_floor,agePossession,Servant Room,Store Room,Pooja Room,Study Room,Others,furnishing_type,luxury_score,Safety,Lifestyle,Environment,Connectivity,Grean Area,Management,Construction,Amenities
0,house,5,70A,bptp visionnaire,5.25,20115.0,2610.0,NA,NA,NA,5.0,4.0,4.0,North-East,NA,3.0,New Property,1,0,0,0,0,1,56.0,4,4,5,4,NA,NA,NA,NA
1,house,10,43,independent,2.1,38251.0,549.0,NA,NA,NA,10.0,10.0,4.0,West,NA,5.0,New Property,1,0,0,0,0,1,56.0,5,5,5,5,NA,NA,NA,NA
2,house,21,54,independent,5.0,43066.0,1161.0,NA,NA,NA,21.0,21.0,4.0,North,NA,5.0,Relatively New,1,0,0,0,0,2,27.0,4,5,4,4,NA,NA,NA,NA
3,house,12,43,independent,3.0,53763.0,558.0,NA,NA,NA,12.0,12.0,4.0,West,NA,5.0,New Property,0,0,0,0,1,2,29.0,5,5,5,5,NA,NA,NA,NA
4,house,20,43,independent,4.5,39062.0,1152.0,NA,NA,NA,20.0,20.0,4.0,East,NA,4.0,Relatively New,1,0,0,0,0,2,135.0,5,5,5,5,NA,NA,NA,NA

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936 entries, 0 to 935
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   type              936 non-null    object
 1   bhk               936 non-null    int64
 2   sector            936 non-null    object
 3   society           936 non-null    object
 4   price             936 non-null    object
 5   price_sqft        936 non-null    object
 6   plot_area         936 non-null    object
 7   carpet_area       936 non-null    object
 8   build_area        936 non-null    object
 9   super_build_area  936 non-null    object
 10  bedroom           936 non-null    object
 11  bathroom          936 non-null    object
 12  balcony           936 non-null    object
 13  facing            936 non-null    object
 14  flat_floor        936 non-null    object
 15  house_floor       936 non-null    object
 16  agePossession     936 non-null    object
 17  Servant Room      936 non-null    int64
 18  Store Room        936 non-null    int64
 19  Pooja Room        936 non-null    int64
 20  Study Room        936 non-null    int64
 21  Others            936 non-null    int64
 22  furnishing_type   936 non-null    int64
 23  luxury_score      936 non-null    object
 24  Safety            936 non-null    int64
 25  Lifestyle         936 non-null    int64
 26  Environment       936 non-null    int64
 27  Connectivity      936 non-null    int64
 28  Grean Area        936 non-null    object
 29  Management        936 non-null    object
 30  Construction      936 non-null    object
 31  Amenities         936 non-null    object
dtypes: int64(11), object(21)
memory usage: 234.1+ KB

In [11]:
df2 = pd.concat([df,df1], ignore_index=False)

In [12]:
df2.head()

,type,bhk,sector,society,price,price_sqft,plot_area,carpet_area,build_area,super_build_area,bedroom,bathroom,balcony,facing,flat_floor,house_floor,agePossession,Servant Room,Store Room,Pooja Room,Study Room,Others,furnishing_type,luxury_score,Environment,Amenities,Lifestyle,Construction,Management,Grean Area,Connectivity,Safety
0,flat,2.0,33,tulsiani easy in homes,0.4,6722.0,NA,595.0,NA,NA,2.0,2.0,3.0,NA,12.0,NA,New Property,0,0,0,0,0,0,0.0,4,0,4,0,0,0,5,4
1,flat,2.0,61,smart world orchard,1.47,12250.0,NA,1200.0,NA,NA,2.0,2.0,2.0,NA,2.0,NA,Undefined,0,0,0,1,0,0,0.0,0,0,0,0,0,0,0,0
2,flat,2.0,92,parkwood westend,0.7,5204.0,NA,NA,1345.0,NA,2.0,2.0,3.0,NA,5.0,NA,Under Construction,0,0,0,1,0,0,89.0,5,0,4,0,0,0,4,3
3,flat,2.0,36,signature global infinity mall,0.41,6269.0,NA,NA,NA,654.0,2.0,2.0,3.0,NA,3.0,NA,Undefined,0,0,0,0,0,0,72.0,0,0,0,0,0,0,0,0
4,flat,3.0,104,ats triumph,1.8,7860.0,NA,2290.0,NA,NA,3.0,4.0,3.0,NA,14.0,NA,New Property,0,0,0,0,0,0,54.0,0,0,0,5,5,4,5,0

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3786 entries, 0 to 935
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   type              3786 non-null   object
 1   bhk               3786 non-null   float64
 2   sector            3786 non-null   object
 3   society           3786 non-null   object
 4   price             3786 non-null   object
 5   price_sqft        3786 non-null   object
 6   plot_area         3786 non-null   object
 7   carpet_area       3786 non-null   object
 8   build_area        3786 non-null   object
 9   super_build_area  3786 non-null   object
 10  bedroom           3786 non-null   object
 11  bathroom          3786 non-null   object
 12  balcony           3786 non-null   object
 13  facing            3786 non-null   object
 14  flat_floor        3786 non-null   object
 15  house_floor       3786 non-null   object
 16  agePossession     3786 non-null   object
 17  Servant Room      3786 non-null   int64
 18  Store Room        3786 non-null   int64
 19  Pooja Room        3786 non-null   int64
 20  Study Room        3786 non-null   int64
 21  Others            3786 non-null   int64
 22  furnishing_type   3786 non-null   int64
 23  luxury_score      3786 non-null   object
 24  Environment       3786 non-null   int64
 25  Amenities         3786 non-null   object
 26  Lifestyle         3786 non-null   int64
 27  Construction      3786 non-null   object
 28  Management        3786 non-null   object
 29  Grean Area        3786 non-null   object
 30  Connectivity      3786 non-null   int64
 31  Safety            3786 non-null   int64
dtypes: float64(1), int64(10), object(21)
memory usage: 976.1+ KB

In [14]:
df2.to_csv('flat-house.csv', index=False)